import {Axios} from "axios";
import {env} from "../configs/envConfig";

/**
 * Fetches the team member data.
 *
 * @returns {Array<Object>} If successful: Array of objects where each object has the following fields:
 * - `name` (string, always present)
 * - `role` (string, always present)
 * - `specificRole` (string, sometimes present) : 'developer' | 'designer' | 'operations' | 'finance'
 * - `profileImage` (url string, always present)
 * - `profileLink` (url string, always present)
 * - `bio` (string, sometimes present)
 * @returns {Array<Object>} If error: Array with the first object containing an `error` field with the error description.
 */
export async function getTeamMemberData(){

    return [

        {
            name: 'Coming soon',
            role: '',
            profilePicture: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
            profileLink: '/', // This can be linked in or any other link we choose
            bio: 'Details of the members of our team are coming soon!',
        },
        {
            name: 'Coming soon',
            role: '',
            profilePicture: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
            profileLink: '/', // This can be linked in or any other link we choose
            bio: 'Details of the members of our team are coming soon!',
        },
        {
            name: 'Coming soon',
            role: '',
            profilePicture: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
            profileLink: '/', // This can be linked in or any other link we choose
            bio: 'Details of the members of our team are coming soon!',
        },
        {
            name: 'Coming soon',
            role: '',
            profilePicture: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
            profileLink: '/', // This can be linked in or any other link we choose
            bio: 'Details of the members of our team are coming soon!',
        },
    ];
}

/**
 * Fetches the team member data.
 *
 * @returns {Array<Object>} If successful: Array of objects where each object has the following fields:
 * - `name` (string, always present)
 * - `role` (string, always present)
 * - `specificRole` (string, sometimes present) : 'developer' | 'designer' | 'operations' | 'finance'
 * - `profileImage` (url string, always present)
 * - `profileLink` (url string, always present)
 * - `bio` (string, sometimes present)
 * @returns {Array<Object>} If error: Array with the first object containing an `error` field with the error description.
 */
export async function getTeamMemberDataNew(){
    try{
        const fetchedData = Axios.get(`${env.backendUrl}/api/team`);
        let translatedMemberData = []; // {Array<Object>}

        fetchedData.array.forEach(element => {
            const name = fetchedData.name;
            const role = fetchedData?.role || null; // TODO: Add type check for 'developer' | 'designer' | 'operations' | 'finance'
            const profilePicture = fetchedData.profilePicture;
            const profileLink = fetchedData?.profileLink || null;
            const linkedIn = fetchedData.linkedIn;
            const website = fetchedData.website;
            const bio = fetchedData?.bio || null;
            translatedMemberData.push({name: name, role: role, profilePicture: profilePicture, profileLink: profileLink, bio: bio, linkedIn: linkedIn, website: website});
        });

        return fetchedData; 
    } catch(error){
        return [{error: 'Error fetching data, please try again later'}];
    }
}

/**
 * Create an array of objects, of all the team members from the team member directory.
 * Example of an individual object:
 * ```js
 * {
 * name: `Vijit Dua`,
 * profilePicture: `${process.env.PUBLIC_URL}/profile-images/vijit-dua.png`,
 * linkedIn: `https://linkedin.com/in/vijitdua`,
 * website: `https://vijitdua.com/socials`,
 * },
 * ```
 *
 * name and profile picture are required
 *
 * linkedIn and website are optional, so put them for members that have them and not for the ones that don't.
 *
 * Get data from the google drive assets folder and upload profile-images with the format firstname-lastname.extension
 * to the profile/images directory in the public folder.
 *
 * Appropriately link them using the public_url process.env as shown above
 *
 * Then add the names too ofcourse.
 */


export const teamMembers = [
    {
        name: `Alberto Gazzato`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/alberto-gazzato-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/alberto-gazzato-3743aa191/`,
        website: `https://www.artstation.com/albertogazzato`,
    },
    {
        name: `Alex Clark`,
        role: 'Level Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/alex-clark-1.jpg`,
        linkedIn: `https://www.https://www.linkedin.com/in/alexclarkld/`,
        website: `https://www.acgamingnow.com`,
    },
    {
        name: `Alexa Cotto`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/alexa-cotto-1.png`,
        linkedIn: `https://www.linkedin.com/in/alexa-cotto-613310243/`,
        website: `https://artoflexmon.portfoliobox.net/art-of-lexmon`,
    },
    {
        name: `Alexis Lydon`,
        role: 'Developer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/alexis-lydon-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/alexis-lydon-477498223/`,
        website: `https://github.com/alexisbl14`,
    },
    {
        name: `Amanda Torres`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/amanda-torres-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/amandamatorres/`,
        website: `https://www.artstation.com/amandastardust`,
    },
    {
        name: `Andrea Buonocore`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/andrea-buonocore-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/andrea-buonocore-8b0198216/`,
        website: `https://andreabuonocore50.wixsite.com/andreabuonocore`,
    },
    {
        name: `Andre-Jon Albino`,
        role: 'Videographer - Media Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/aandre-jon-albino-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/andr%C3%A9-jon-albino-1834b4163/`,
        website: `https://andre-albino.digital/video-projects`,
    },
    {
        name: `Andrew Bainard`,
        role: 'Project Manager - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/andrew-bainard-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/andrewbainard`,
        website: `https://www.artstation.com/andrewbainard`,
    },
    {
        name: `Andrew Davidson`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/andrew-davidson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/andrew-davidson-534375130/`,
        website: `https://aforangers.wixsite.com/andrewdavidsoniii`,
    },
    {
        name: `Angelyna Doan`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/angelyna-doan-1.jpg`,
        linkedIn: `http://linkedin.com/in/angelyna-doan`,
        website: `https://angelynadoan.nolioportfolio.com/work`,
    },
    {
        name: `Anika Jorgensen`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/anika-jorgensen-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/anikajorgensen/`,
        website: `https://anikasportfolio.squarespace.com/`,
    },
    {
        name: `Anna Alekseeva`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/anna-alekseeva-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/anna-alekseeva-959542238/`,
        website: `https://www.artstation.com/annamilad`,
    },
    {
        name: `Anson Au`,
        role: 'Environmental Prop Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/anson-au-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/anson-au-152a871b7/`,
        website: null,
    },
    {
        name: `Artem Klymuk`,
        role: 'Environmental Prop Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/artem-klymuk-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/artemks`,
        website: `https://www.artstation.com/artem_ks`,
    },
    {
        name: `Ashley Caroll`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/ashley-caroll-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/ashleycarroll123/`,
        website: `https://www.artstation.com/ashleycarroll`,
    },
    {
        name: `Athul Haridas`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/athul-haridas-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/athul-haridas-3dartist`,
        website: `https://80.lv/talent/p/athul-haridas`,
    },
    {
        name: `Aubrey Spencer`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/aubrey-spencer-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/aubrey-spencer-430853249/`,
        website: `https://aubreyspencerartis.wixsite.com/aubreyspencerart`,
    },
    {
        name: `Aung Kyaw`,
        role: 'Developer - Mobile Games Division, Web Development',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/aung-kyaw-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/aungkkyaw/`,
        website: `https://aungkhantkyaw.netlify.app/`,
    },
    {
        name: `Autry George`,
        role: '3D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/autry-george-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/autry-george-757ab2154/`,
        website: `https://www.artstation.com/autrygeorge4`,
    },
    {
        name: `Axel Luis Servin`,
        role: 'Sound Designer - Audio Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/axel-gomez-servin-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/axel-luis-gomez-servin-9979a5220/`,
        website: `https://axelgomezservinaudio.weebly.com/`,
    },
    {
        name: `Blase Henry`,
        role: 'Writer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/blase-henry-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/blase-henry-510935137/`,
        website: `https://blasesportfolio.wordpress.com/`,
    },
    {
        name: `Bray Chandler`,
        role: 'Developer - Web Development',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/bray-chandler-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/bray-chandler/`,
        website: `https://braychandlergamewriter.squarespace.com/`,
    },
    {
        name: `Brian Kwon`,
        role: 'Developer - Web Development',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/brian-kwon-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/briankwon3702`,
        website: `https://https://github.com/kwon-23`,
    },
    {
        name: `Brittany Lamont`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/brittany-lamont-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/brittany-lamont-3b2339112/`,
        website: `https://brittanylamont.wixsite.com/brittanylamont`,
    },
    {
        name: `Bryant Cachola`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/bryant-cachola-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/bryant-cachola/`,
        website: `https://www.artstation.com/bcachola`,
    },
    {
        name: `Bryce Kadash`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/bryce-kadash-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/bryce-kadash`,
        website: `https://www.artstation.com/bkadash`,
    },
    {
        name: `Bryce Lim`,
        role: '2D Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/bryce-lim-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/bryce-lim-4ba752266/`,
        website: `https://brycelimart.wixsite.com/work`,
    },
    {
        name: `Caio Simonetta`,
        role: 'Operational Manager',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/caio-simonetta-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/caio-simonetta-474a29270/`,
        website: `https://muse.io/csimonetta`,
    },
    {
        name: `Calder Swiderski`,
        role: 'Game Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/calder-swiderski-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/calderswiderski`,
        website: `https://www.calderswiderski.com/`,
    },
    {
        name: `Caleigh Gorcoff`,
        role: 'Concept Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/caleigh-gorcoff-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/caleigh-gorcoff-295422238/`,
        website: `https://www.artstation.com/creneeart`,
    },
    {
        name: `Calvin Kim`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/calvin-kim-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/calvinkim010896/`,
        website: `https://www.artstation.com/calvinkimart`,
    },
    {
        name: `Chaewoon Hyun`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/chaewoon-hyun-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/chaewoon-hyun-art/`,
        website: `https://codns.artstation.com/`,
    },
    {
        name: `Charles Howerton`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/charles-howerton-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/charles-howerton-41545622a/`,
        website: `https://www.artstation.com/howertonconceptart`,
    },
    {
        name: `Chloe Nguyen`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/chloe-nguyen-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/chloe-doanh-nguyen-008682161/`,
        website: `https://www.artstation.com/chloenguyen`,
    },
    {
        name: `Chris Freeman`,
        role: 'Level Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/chris-freeman-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/chris-freeman-49b874221`,
        website: `https://odstudiocom.wixsite.com/obsidian-dawn-studio`,
    },
    {
        name: `Chris Ramos`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/chris-ramos-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/chrisramosart/`,
        website: `https://www.artstation.com/chris_r64`,
    },
    {
        name: `Clay Bryner`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/clay-bryner-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/clay-bryner/`,
        website: `https://www.claybryner.com/portfolio`,
    },
    {
        name: `Clay Tingue`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/clay-tingue-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/clay-tingue-633911305/`,
        website: `https://tinguecd.myportfolio.com/`,
    },
    {
        name: `Colton Taylor`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/colton-taylor-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/colton-taylor-lvd/`,
        website: `https://ctaylorb1221.wixsite.com/colton-taylor`,
    },
    {
        name: `Connie Chau`,
        role: 'Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/connie-chau-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/tszkiconniechau/`,
        website: `https://www.conniechau.com/`,
    },
    {
        name: `Daniel Herranz`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/daniel-herranz-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/daniel-herranz/`,
        website: `https://www.artstation.com/danielheranz`,
    },
    {
        name: `Denny Siliezar`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/denny-siliezar-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/denny-siliezar-108ba5191/`,
        website: `https://marinesgalaxy.artstation.com/`,
    },
    {
        name: `Devin Sanchez`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/devin-sanchez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/devmatsan/`,
        website: `https://www.artstation.com/huntthepear`,
    },
    {
        name: `Diego Lazo`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/diego-lazo-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/diego-lazo-b57796181/`,
        website: `http://www.artstation.com/diego_lazo`,
    },
    {
        name: `Dillon Heeke`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/dillon-heeke-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/dillon-heeke-361277158/`,
        website: `https://www.artstation.com/dillonheeke`,
    },
    {
        name: `Dziana Vasilevich`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/dziana-vasilevich-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/dziana-vasilevich-0ab65b284/`,
        website: `https://www.artstation.com/diana_vasilevich`,
    },
    {
        name: `Ekaterina Ponomarenko`,
        role: '3D Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/ekaterina-ponomarenko-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/ekaterina-ponomarenko-aaa0a6320/`,
        website: `https://www.artstation.com/studel`,
    },
    {
        name: `Emil Saechao`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/emil-saechao-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/emil-saechao/`,
        website: `https://www.artstation.com/ehmeal`,
    },
    {
        name: `Emile Tilleman`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/emile-tilleman-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/emile-tilleman/`,
        website: `https://emilesportfolio.framer.website/`,
    },
    {
        name: `Erin Lawson`,
        role: 'Project Lead - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/erin-lawson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/erinlawson001`,
        website: `https://www.erinlawsonsart.com/`,
    },
    {
        name: `Evan Wanamaker`,
        role: 'Writer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/evan-wanamaker-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/evanwanamaker/`,
        website: null,
    },
    {
        name: `Fia McCord`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/fia-mccord-1.jpg`,
        linkedIn: `https://linkedin.com/in/fia-mccord-6ba418238`,
        website: `https://artmccordfi.wixsite.com/my-site-1`,
    },
    {
        name: `Francesca Jassir`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/francesca-jassir-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/francesca-jassir-noguera-40152b226/`,
        website: `https://www.francescajassir.com/animation`,
    },
    {
        name: `Gabriel Jaluize`,
        role: 'Audio - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/gabriel-jaluize-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/gabriel-jaluize/`,
        website: `https://gabrieljaluize.carrd.co/`,
    },
    {
        name: `Gabrielle Matheson`,
        role: 'UI/UX Designer - Web Dev Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/gabrielle-matheson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/gabrielle-matheson-753161285/`,
        website: null,
    },
    {
        name: `Gaia Whitehead`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/gaia-whitehead-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/gaia-whitehead-80098a1b8/`,
        website: `https://whiteheadgaia.artstation.com/`,
    },
    {
        name: `Galo Domaica`,
        role: 'Project Manager - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/galo-domaica-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/galo-domaica-6681ba14a/`,
        website: `https://watermelon-saxophone-zc2g.squarespace.com/`,
    },
    {
        name: `Guy Doratio Jr.`,
        role: '3D Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/guy-doratio-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/guy-doratio/`,
        website: `https://guydoratio.artstation.com/projects`,
    },
    {
        name: `Hallee Martinez`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/hallee-martinez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/hallena-martinez-3317a1207/?utm_sou`,
        website: `https://www.artstation.com/fantasymyths`,
    },
    {
        name: `Hannah Perez`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/hannah-perez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/hannah-perez-099547351/`,
        website: `https://hannahperezart.wixsite.com/my-site-1`,
    },
    {
        name: `Hari Prasad`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/hari-peram-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/hari-chandra-prasad-9029a0127/`,
        website: `https://www.artstation.com/artwork/1xe3kL`,
    },
    {
        name: `Hayden Krider`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/hayden-krider-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/hayden-krider-3092b826a/`,
        website: `https://hkridr.wixstudio.com/h2k2`,
    },
    {
        name: `Honghui Henry Li`,
        role: 'Developer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/honghui-henry-li-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/honghui-li-789b9a24a/`,
        website: `https://github.com/Honghui-Li-8`,
    },
    {
        name: `Ian Pillai`,
        role: 'Audio - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/ian-pillai-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/ian-pillai-502899224`,
        website: `https://youtu.be/a-JhMiTPGSc`,
    },
    {
        name: `Jaden Corrado`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jaden-corrado-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jaden-corrado/`,
        website: `https://www.jadencorrado.com/`,
    },
    {
        name: `Janelle Pereyda`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/janelle-pereyda-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/janellep3191/`,
        website: `https://www.artstation.com/sweetlemonaaade`,
    },
    {
        name: `Jason Donohoo`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jason-donohoo-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jason-donohoo-6ab3b7322`,
        website: `https://sites.google.com/view/jdonohoogamedesignportfolio/home`,
    },
    {
        name: `Jeremy Layseca`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jeremy-layseca-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jeremy-layseca/`,
        website: `https://jeremylayseca.wixsite.com/jeremylayseca`,
    },
    {
        name: `Jeremy Martinez`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jeremy-martinez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jemmavs/`,
        website: `https://www.artstation.com/jemmavs`,
    },
    {
        name: `Joanne Lee`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/joanne-lee-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/joanne-lee-885a1721a/`,
        website: `https://www.artstation.com/joannelee`,
    },
    {
        name: `Jobeth Fondren`,
        role: '3D Rigging - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jobeth-fondren-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jobeth-fondren202`,
        website: `https://www.Jobethfondren6.artstation.com`,
    },
    {
        name: `John Overton`,
        role: 'Team Lead, Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/john-overton-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/johnovertonid/`,
        website: `https://github.com/4554551NX`,
    },
    {
        name: `Johnathan Burnett`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/johnathan-burnett-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/johnathan-logan-burnett/`,
        website: null,
    },
    {
        name: `Johnathan Rios`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/johnathan-rios-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/johnathan-rios-4b232020b/`,
        website: `https://www.artstation.com/johnathan_rios`,
    },
    {
        name: `Jonah Hoem`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jonah-hoem-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jonah-hoem-ab3a79172/`,
        website: `https://www.artstation.com/jonahhoem`,
    },
    {
        name: `Jordan Garcia`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jordan-garcia-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jordan-garcia-587ab41b6/`,
        website: `https://www.artstation.com/jordan_garcia33`,
    },
    {
        name: `Jordan Reavis`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jordan-reavis-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jordan-reavis-147992259/`,
        website: `https://reavisjordan.github.io/portfolio/`,
    },
    {
        name: `Joseph Kozubowski`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/joseph-kozubowski-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/joseph-kozubowski-8b031a1b4/`,
        website: `https://www.artstation.com/joseph_kozubowski`,
    },
    {
        name: `Josiah Jones`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/josiah-jones-1.jpg`,
        linkedIn: `http://linkedin.com/in/josiah-jones-987b7a257`,
        website: `https://josiahjones65.wixsite.com/josiahjonesportfolio`,
    },
    {
        name: `Joyel Joseph`,
        role: 'Project Lead - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/joyel-joseph-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/joyel-joseph-7772252b6/`,
        website: `https://joejoseph6.wixsite.com/joyel`,
    },
    {
        name: `Jude Key`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/jude-key-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/jude-key-20351a1b7/`,
        website: `https://www.judekey.com/`,
    },
    {
        name: `Julian Lara`,
        role: 'Developer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/julian-lara-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/julian-m-lara/`,
        website: `https://github.com/JuiceBox7`,
    },
    {
        name: `Justin Gozal`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/justin-gozal-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/justin-gozal-10166519b/`,
        website: `https://www.artstation.com/jgozalart`,
    },
    {
        name: `Justin Tollison`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/justin-tollison-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/justintollison/`,
        website: null,
    },
    {
        name: `Kaden Marler`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kaden-marler-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kaden-marler-b71149140/`,
        website: `https://marlerkadenr.wixsite.com/porfolio`,
    },
    {
        name: `Kaitlyn Pislaan`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kaitlyn-pislaan-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kaitlyn-p-a49451233/`,
        website: `https://www.artstation.com/kpislaan`,
    },
    {
        name: `Keven Dixon`,
        role: 'Videographer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/keven-dixon-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/keven-dixon-4434421b5/`,
        website: `https://vimeo.com/760163383`,
    },
    {
        name: `Kirill Lavrukov`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kirill-lavrukov-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kirill-lavrukov/`,
        website: `https://www.artstation.com/fullmetalbeton`,
    },
    {
        name: `Kris Rogers`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kris-rogers-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kris-rogers/`,
        website: `https://www.artstation.com/krisrogers73`,
    },
    {
        name: `Kristian Chavez`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kristian-chavez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kristian-chavez-976a1a188/`,
        website: `https://captainpinacoladai.wixsite.com/kristianchavez`,
    },
    {
        name: `Kristofferson Espiritu`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kristofferson-espiritu-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kristofferson-espiritu/`,
        website: `https://www.espirit2designs.com/`,
    },
    {
        name: `Kyle Reed`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/kyle-reed-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/kyle-reed-8a751a222/`,
        website: `https://github.com/KyleXR`,
    },
    {
        name: `Lauren Hill`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lauren-hill-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/laurenhill0425/`,
        website: `https://www.artstation.com/laurenhi11`,
    },
    {
        name: `Lauren Mulzer`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lauren-mulzer-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lauren-mulzer-a41b14224/`,
        website: `https://www.laurenmulzer.com/`,
    },
    {
        name: `Lia Gonzalez`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lia-gonzalez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lia-gonzalez-090b442b4/`,
        website: `https://cherryblossomcreat0.wixsite.com/my-site-2`,
    },
    {
        name: `Lily Inman`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lily-inman-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lily-inman-b3a182209/`,
        website: `https://www.lilyinman.com/`,
    },
    {
        name: `Lucas Casali`,
        role: 'Composer - Audio Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lucas-casali-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lucas-casali-0847a71ab/`,
        website: `https://open.spotify.com/artist/5FcRF2Cx18l7I3jGwc3LA1?si=c-kBiqKQRxqlnI9ucWboAQ&nd=1&dlsi=9f9fcb80846349bb`,
    },
    {
        name: `Lucas Sanchez`,
        role: 'Narrative Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lucas-sanchez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lucas-sanchez-2002`,
        website: `https://lucasp0326.github.io/`,
    },
    {
        name: `Lukas Lopez`,
        role: 'Marketing Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/lukas-lopez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/lukasdlopez/`,
        website: `https://lukasdlopez.myportfolio.com/`,
    },
    {
        name: `Mac Burkemper`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/mac-burkemper-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/adam-burkemper-jr-2321b7251/`,
        website: `https://macburkemper.wixsite.com/my-site`,
    },
    {
        name: `Madison Trembley`,
        role: 'Writer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/madison-trembley-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/madison-trembley-4537b8262/`,
        website: `https://madisontrembley.wixsite.com/madison-trembley`,
    },
    {
        name: `Maggie Ma`,
        role: 'UI/UX Designer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/maggie-ma-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/maggiema209/`,
        website: `https://maggiema.com/`,
    },
    {
        name: `Marc Paolo Yap`,
        role: 'Project Lead - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/marc-paolo-yap-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/marc-paolo-yap/`,
        website: `https://github.com/paoloyap22`,
    },
    {
        name: `Mariana Homsy`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/mariana-homsy-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/marianahomsy/`,
        website: `https://www.artstation.com/dahabd`,
    },
    {
        name: `Marina (Mer) Rose`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/marina-rose-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/scrimbie/`,
        website: `https://scrimbie.com/`,
    },
    {
        name: `Maritzell Martinez`,
        role: 'Graphic Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/maritzell-martinez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/maritzell-martinez-67b268181`,
        website: `https://maritzellm.carrd.co/`,
    },
    {
        name: `Maryana Bartkiv`,
        role: 'Graphic Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/maryana-bartkiv-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/maryana-bartkiv-4339a6311/`,
        website: `https://www.artstation.com/reskords`,
    },
    {
        name: `Matthew Stecker`,
        role: 'Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/matthew-stecker-1.jpg`,
        linkedIn: `https://linkedin.com/in/mdstecker/`,
        website: `https://www.mdsteckerportfolio.com/`,
    },
    {
        name: `Maxim Shirkov`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/maxim-shirkov-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/maxim-shirkov-5a35b2211/`,
        website: `https://www.artstation.com/solventum`,
    },
    {
        name: `Maytavin Pongsudhiraks`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/maytavin-pongsudhiraks-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/maytavin-pongsudhiraks-a67356264/`,
        website: `https://mattpong.com/`,
    },
    {
        name: `Megan Dinizio`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/megan-dinizio-1.jpg`,
        linkedIn: `http://linkedin.com/in/megan-dinizio-vfx`,
        website: `https://mdiniziovfx.com/14-2/`,
    },
    {
        name: `Megan Melberg`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/megan-melberg-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/meganmelberg/`,
        website: `https://www.artstation.com/meganmelberg14/albums/4678043`,
    },
    {
        name: `Michael Santiago`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/michael-santiago-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/michael-santiago-22a337141/`,
        website: `https://michaelsantiago.artstation.com/`,
    },
    {
        name: `Michael Wan`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/michael-wan-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/michaelwan99`,
        website: `https://www.artstation.com/michaelwan`,
    },
    {
        name: `Micah Landeros`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/micah-landeros-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/micahlanderos33`,
        website: `https://artstation.com/micahlanderos1`,
    },
    {
        name: `Michelle Vu`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/michelle-vu-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/michelle-vu-a3443016b`,
        website: `https://www.artstation.com/michelle_vu`,
    },
    {
        name: `Miguel Lopez`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/miguel-lopez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/miguel-lopez-ab756b253/`,
        website: `https://miguelgamedesign.weebly.com/`,
    },
    {
        name: `Miles Stevenson`,
        role: 'IT Technician',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/miles-stevenson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/miles-stevenson-334baa300/`,
        website: null,
    },
    {
        name: `Nadine Nakamura`,
        role: '2D Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/nadine-nakamura-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/nadine-nakamura-a44195273/`,
        website: `https://www.behance.net/nadinenakamura/projects`,
    },
    {
        name: `Najee Jackson`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/najee-jackson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/najee-jackson-5312a5253/`,
        website: `https://najeejacksonportfolio.wordpress.com/`,
    },
    {
        name: `Nanxiang Wang`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/nanxiang-wang-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/nanxiang-wang-174014204/`,
        website: `https://nwang.artstation.com/`,
    },
    {
        name: `Natalia Wozniakowska`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/natalia-wozniakowska-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/natalia-wozniakowska-816411252/`,
        website: `https://www.artstation.com/natwska`,
    },
    {
        name: `Nicholas Stepp`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/nicholas-stepp-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/nicholasstepp`,
        website: `https://www.artstation.com/nstepp2001`,
    },
    {
        name: `Noah King`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/noah-king-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/nkingart/`,
        website: `https://nking-art.webflow.io/`,
    },
    {
        name: `Noemi Ponciroli`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/noemi-ponciroli-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/noemiponciroli/`,
        website: `https://www.artstation.com/noemiponciroli`,
    },
    {
        name: `Nolan Krames`,
        role: 'Operational Manager',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/nolan-krames-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/nolan-krames/`,
        website: `https://www.nolankrames.com/`,
    },
    {
        name: `Olha Tokar`,
        role: '2D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/olha-tokar-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/olha-tokar-13769522a/`,
        website: `https://www.artstation.com/oliatokar`,
    },
    {
        name: `Parker Lee`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/parker-lee-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/parker-lee-910549278/`,
        website: `https://www.artstation.com/parkerlee3`,
    },
    {
        name: `Paulina Procel`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/paulina-procel-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/paulinaprocelosuna/`,
        website: `https://www.artstation.com/pau_procel`,
    },
    {
        name: `Pedro Cosme`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/pedro-cosme-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/pedrocosme/`,
        website: `https://www.artstation.com/pedrocosme/albums/7952732`,
    },
    {
        name: `Platte Clark`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/platte-clark-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/platte-clark-b8375627a/`,
        website: `https://plattinum95.myportfolio.com/`,
    },
    {
        name: `Rama Bit`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/rama-bit-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/rama-bit-236126186/`,
        website: `https://www.artstation.com/sonicfanx1`,
    },
    {
        name: `Reed Miller`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/reed-miller-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/reed-thomas-miller/`,
        website: `https://github.com/ItsTruckMonth`,
    },
    {
        name: `Robert Ehteshamzadeh`,
        role: 'Mentor',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/robert-ehteshamzadeh-1.png`,
        linkedIn: `https://www.linkedin.com/in/rje4242/`,
        website: `https://github.com/rje4242`,
    },
    {
        name: `Rohit Pant`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/rohit-pant-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/rohit-pant`,
        website: `https://www.artstation.com/rohitpant2000`,
    },
    {
        name: `Romeo Mills`,
        role: 'Narrative Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/romeo-mills-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/romeo-mills-259a30258/`,
        website: `https://omeon47.wixsite.com/mysite`,
    },
    {
        name: `Ryan Beattie`,
        role: 'Developer - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/ryan-beattie-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/ryan-beattie-32a35439/`,
        website: `https://www.ryanbeattie.net/`,
    },
    {
        name: `Sabin Overton`,
        role: 'Finance Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sabin-overton-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sabinoverton/`,
        website: null,
    },
    {
        name: `Sasha Tsirin`,
        role: '2D artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sasha-tsirin-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sasha-tsirin-083050219/`,
        website: `https://68a361772026a.site123.me/`,
    },
    {
        name: `Savannah Davis`,
        role: '3D artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/savannah-davis-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/savannah-davis-99b0aa1b8/`,
        website: `https://savannah0402.wixsite.com/website`,
    },
    {
        name: `Sean Yamco`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/savannah-davis-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sean-yamco-754644224/`,
        website: null,
    },
    {
        name: `Sena Sarwari`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sena-sarwari-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sena-sarwari/`,
        website: `https://senasarwari.artstation.com/`,
    },
    {
        name: `Shad Wilde`,
        role: '2D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/shad-wilde-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/shad-wilde-bba31482/`,
        website: `https://www.linkedin.com/in/shad-wilde-bba31482/`,
    },
    {
        name: `Shreyas Nisal`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/shreyas-nisal-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/shreyasnisal`,
        website: `https://reynisal.com/`,
    },
    {
        name: `Simeon Elias`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/simeon-elias-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/scionine/`,
        website: `https://www.simeonelias.com/`,
    },
    {
        name: `Smayaan Marwah`,
        role: 'Project Manager - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/smayaan-marwah-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/smayaan-marwah/`,
        website: `https://www.smayaanmarwah.com/`,
    },
    {
        name: `Son Nguyen`,
        role: 'Project Lead - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/son-nguyen-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/soz48/`,
        website: `https://www.soz48.com/`,
    },
    {
        name: `Sophia Ngo`,
        role: 'Designer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sophia-ngo-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sophia-ngo15/`,
        website: `https://sophiango15.wixsite.com/sophia-ngo`,
    },
    {
        name: `Sounak Kundu`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sounak-kundu-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sounak-kundu-995b69225/`,
        website: `https://www.artstation.com/sounak`,
    },
    {
        name: `Spencer Qiao`,
        role: 'UI/UX Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/spencer-qiao-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/siming-qiao-47153723a/`,
        website: `https://www.thespencerqiao.com/`,
    },
    {
        name: `Stephen DeVito`,
        role: '2D Artist - Indie Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/stephen-devito-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/stephen-devito-b77980250`,
        website: `https://www.artstation.com/goblogar`,
    },
    {
        name: `Sterling Ford`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/sterling-ford-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/sterling-ford-a6593a203/`,
        website: `https://sterlingford.weebly.com/`,
    },
    {
        name: `Steven Chang`,
        role: 'Developer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/steven-chang-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/steven-chang47/`,
        website: `https://github.com/stdChang`,
    },
    {
        name: `Syvan Novom`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/syvan-novom-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/syvannovom/`,
        website: `https://demonicluci.itch.io/`,
    },
    {
        name: `Thomy Alifonso`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/thomy-alifonso-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/thomy-alifonso/`,
        website: `https://www.artstation.com/thomyalifonso`,
    },
    {
        name: `Trevor Bates`,
        role: '3D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/trevor-bates-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/trevor-bates-26548a223/`,
        website: `https://www.trevorbatesanimation.com/`,
    },
    {
        name: `Trevor Goode`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/trevor-goode-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/trevorgoode/`,
        website: `https://www.artstation.com/tagoode`,
    },
    {
        name: `Trinity Ahumada`,
        role: '2D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/trinity-ahumada-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/trinity-ahumada-285271275/`,
        website: `https://trinityahumada.wixsite.com/website`,
    },
    {
        name: `Tristan Dunlop`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/tristan-dunlop-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/tristan-dunlop`,
        website: `https://tristandunlop.com`,
    },
    {
        name: `Vadym Zinkevych`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/vadym-zinkevych-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/vadym-zinkevych`,
        website: `https://tristandunlop.com`,
    },
    {
        name: `Viktoryia Ivashkevich`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/viktoryia-ivashkevich-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/viktoryia-ivashkevich`,
        website: `https://vikkiiv.wixsite.com/portfolio`,
    },
    {
        name: `Viola Di Dilvestre`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/viola-di-silvestre-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/viola-di-silvestre-6401242a2/`,
        website: `https://violadisilvestre.myportfolio.com/`,
    },
    {
        name: `Weena Young Oh`,
        role: 'Writer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/weena-oh-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/weenayoungoh/`,
        website: `https://www.weenayoungoh.com/`,
    },
    {
        name: `William Trang`,
        role: 'Developer - Web Development',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/william-trang-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/williamtrang/`,
        website: `https://github.com/williamtrang`,
    },
    {
        name: `Yihong Li`,
        role: 'Developer - Web Development',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/yihong-li-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/yihongli12/`,
        website: `https://github.com/yihli`,
    },
    {
        name: `Yoona Hwang`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/yoona-hwang-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/yoona-hwang/`,
        website: `https://www.yoonahwang.com/`,
    },
    {
        name: `Yulia Kodlubai`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/yulia-kodlubai-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/yuliakodlubai/`,
        website: `https://www.artstation.com/yulia_kodlubai`,
    },
    {
        name: `Yunmeng Lei`,
        role: '2D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/yunmeng-lei-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/yunmeng-lei-6b5325255/`,
        website: `https://www.artstation.com/whitecake`,
    },
    {
        name: `Yusaku Kimura`,
        role: '3D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/yusaku-kimura-1.jpg`,
        linkedIn: `http://linkedin.com/in/yusaku-k-35a352291`,
        website: `https://vimeo.com/1086619782?share=copy`,
    },
    {
        name: `Zachary Rudewicz-Nepokroeff`,
        role: 'Game Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zachary-rudewicz-nepokroeff-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zachrudynep/`,
        website: `https://zachrudynep.myportfolio.com/`,
    },
    {
        name: `Zachary Selsley`,
        role: 'Developer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zachary-selsley-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zachary-selsley/`,
        website: `https://github.com/Tanuki3017`,
    },
    {
        name: `Zan Moffat`,
        role: 'Technical Designer - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zan-moffat-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zanmoffat`,
        website: `https://fifthmoffat.wixsite.com/zan-moffat`,
    },
    {
        name: `Zoe Benn`,
        role: '3D Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zoe-benn-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zoe-benn-ba15941b8/`,
        website: `https://www.artstation.com/ghostlyzenn`,
    },
    {
        name: `Zofia Paez`,
        role: '2D Concept Artist - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zofia-paez-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zofia-paez-3b08a7297/`,
        website: `https://www.artstation.com/zofiapz`,
    },
    {
        name: `Zion Jefferson`,
        role: '3D Animator - Mobile Games Division',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zion-jefferson-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zion-jefferson-036784237/`,
        website: `https://zarmandjefferson.wixsite.com/znexus`,
    },
    {
        name: `Zoey Vo`,
        role: 'Developer - Davis Dot',
        profilePicture: `${process.env.PUBLIC_URL}/profile-images/zoey-vo-1.jpg`,
        linkedIn: `https://www.linkedin.com/in/zoeyvo`,
        website: `https://zoeyvo.net/`,
    },
];
