backend:
  name: github
  repo: ICARUSALPHAINC/web-frontend 
  branch: production
  base_url: https://cms-auth-dun.vercel.app 
  auth_endpoint: api/login
  
publish_mode: editorial_workflow

media_folder: "public/profile-images" 
public_folder: "/profile-images"

collections:
  - name: "team_data"
    label: "Team Data"
    files:
      - label: "Team Members List"
        name: "team"
        file: "public/team.json" # Points exactly to your new JSON file
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string", required: false}
              - {label: "Profile Picture", name: "profilePicture", widget: "image"}
              - {label: "LinkedIn", name: "linkedIn", widget: "string", required: false}
              - {label: "Website", name: "website", widget: "string", required: false}