name: Deploy to SSH Machine

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove existing files from the Web Frontend directory
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          echo 'Removing old files...'
          sudo rm -rf /home/vijit/Web\ Frontend/*
        "
    
    - name: Clean up Docker resources
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          sudo docker system prune -af
          sudo docker volume prune -f
        "

    - name: Copy new files to SSH machine
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --no-perms --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/vijit/Web\ Frontend

    - name: Stop and remove old containers
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          echo 'Stopping and removing existing container...'
          CONTAINER_ID=\$(sudo docker ps -aq --filter name=web-frontend-container)
          if [ ! -z \"\$CONTAINER_ID\" ]; then
            echo 'Stopping container with ID: \$CONTAINER_ID'
            sudo docker stop \$CONTAINER_ID || true
            echo 'Removing container with ID: \$CONTAINER_ID'
            sudo docker rm -f \$CONTAINER_ID
          else
            echo 'No running container found'
          fi

          echo 'Stopping and removing containers running on port 5002...'
          PORT_CONTAINERS=\$(sudo docker ps -q --filter "publish=5002")
          if [ ! -z \"\$PORT_CONTAINERS\" ]; then
            sudo docker stop \$PORT_CONTAINERS || true
            sudo docker rm -f \$PORT_CONTAINERS
          fi
        "

    - name: Build Docker image
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          echo 'Building Docker image...'
          cd /home/vijit/Web\ Frontend && sudo docker build . -t web-frontend
        "

    - name: Run new Docker container
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          echo 'Starting new container...'
          sudo docker run -d -p 5002:3000 --restart=always --name web-frontend-container web-frontend
        "
